name: All tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  xteps_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Maven test
      run: mvn -B clean test --file xteps/pom.xml
  xteps_allure_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Maven test
      run: mvn -B clean test --file xteps-allure/pom.xml
  xteps_reportportal_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Maven test
      run: mvn -B clean test --file xteps-reportportal/pom.xml
